spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: user
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: validate
  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 9MB

amazon-properties:
  bucketName: file-uploader-s3
